[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = [
    'cp .env.mysql .env',
    'npm run build',
    'php artisan key:generate --force',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'