[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "npm"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/"