[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.fileinfo", "php82Extensions.tokenizer", "php82Extensions.ctype", "php82Extensions.json", "php82Extensions.bcmath", "php82Extensions.openssl"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build"]

[start]
cmd = "chmod -R 775 storage bootstrap/cache && php artisan key:generate --force && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan migrate --force || echo 'Migration failed, continuing...' && php -S 0.0.0.0:$PORT -t public/"