[phases.setup]
nixPkgs = ['...', 'php82', 'php82Packages.composer', 'apache2']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/'